name: Fancam Ranker Daily

on:
  schedule:
    - cron: "0 12 * * *" # Executa todos os dias às 12:00 UTC (09:00 no Brasil)
  workflow_dispatch: # Permite rodar manualmente

jobs:
  run-fancam-ranker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Fancam Ranker
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          python youtube_fancam_ranker.py
